import { Project, LeaderboardEntry } from './types';

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, username: "Jesse.base", points: 15400, avatar: "https://picsum.photos/seed/jesse/50/50", badges: ["🐳", "🔥"] },
  { rank: 2, username: "BrianA.eth", points: 12250, avatar: "https://picsum.photos/seed/brian/50/50", badges: ["💎"] },
  { rank: 3, username: "BasedGod", points: 9800, avatar: "https://picsum.photos/seed/god/50/50", badges: ["🚀", "🔵"] },
  { rank: 4, username: "BluePill", points: 8500, avatar: "https://picsum.photos/seed/blue/50/50", badges: ["💊"] },
  { rank: 5, username: "WagmiWarrior", points: 7200, avatar: "https://picsum.photos/seed/wagmi/50/50", badges: [] },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Based Pepes',
    description: 'The ultimate collection of rare Pepes native to the Base chain. Combining meme culture with DeFi mechanics.',
    logo: 'https://picsum.photos/seed/pepe/200/200',
    banner: 'https://picsum.photos/seed/pepebanner/1200/400',
    softCap: 50,
    hardCap: 200,
    raised: 155,
    backers: 420,
    tokenTicker: '$BPEPE',
    tokenomics: [
      { name: 'Liquidity', value: 60, fill: '#0052FF' },
      { name: 'Team', value: 10, fill: '#333' },
      { name: 'Airdrop', value: 30, fill: '#00D1FF' },
    ],
    comments: [
        { id: 'c1', user: 'BasedGod', text: 'This is going to moon hard 🚀', timestamp: Date.now() - 1000000 },
        { id: 'c2', user: 'PepeLover', text: 'Finally a good meme on Base', timestamp: Date.now() - 500000 }
    ],
    sketchiness: [
      { subject: "Team", A: 20, fullMark: 100 },
      { subject: "Code", A: 10, fullMark: 100 },
      { subject: "Hype", A: 80, fullMark: 100 },
      { subject: "Utility", A: 90, fullMark: 100 }, 
      { subject: "Audit", A: 30, fullMark: 100 },
    ],
    prediction: { yes: 1200, no: 45 },
    category: 'Meme',
    miningEntryCost: 0.1,
    daoRights: true,
    status: 'Funding'
  },
  {
    id: '2',
    title: 'Blue DeFi',
    description: 'A decentralized exchange aggregator optimized for Base L2 low fees. Swap instantly with zero slippage.',
    logo: 'https://picsum.photos/seed/defi/200/200',
    banner: 'https://picsum.photos/seed/defibanner/1200/400',
    softCap: 100,
    hardCap: 500,
    raised: 80,
    backers: 120,
    tokenTicker: '$BLUE',
    tokenomics: [
      { name: 'Public', value: 50, fill: '#0052FF' },
      { name: 'Treasury', value: 25, fill: '#1e293b' },
      { name: 'Team', value: 25, fill: '#94a3b8' },
    ],
    comments: [],
    sketchiness: [
      { subject: "Team", A: 10, fullMark: 100 },
      { subject: "Code", A: 5, fullMark: 100 },
      { subject: "Hype", A: 40, fullMark: 100 },
      { subject: "Utility", A: 10, fullMark: 100 },
      { subject: "Audit", A: 10, fullMark: 100 },
    ],
    prediction: { yes: 340, no: 120 },
    category: 'DEX',
    miningEntryCost: 0.5,
    daoRights: true,
    status: 'Funding'
  },
  {
    id: '3',
    title: 'Pixel Base',
    description: 'An open-world MMORPG entirely on-chain. Your assets are your stats. Play to earn Base ETH.',
    logo: 'https://picsum.photos/seed/pixel/200/200',
    banner: 'https://picsum.photos/seed/pixelbanner/1200/400',
    softCap: 20,
    hardCap: 100,
    raised: 120, // Over hardcap example
    backers: 890,
    tokenTicker: '$PIXL',
    tokenomics: [
      { name: 'Game Rewards', value: 70, fill: '#0052FF' },
      { name: 'Dev', value: 30, fill: '#ffffff' },
    ],
    comments: [
        { id: 'c3', user: 'GamerOne', text: 'Cant wait for beta', timestamp: Date.now() }
    ],
    sketchiness: [
       { subject: "Team", A: 50, fullMark: 100 },
       { subject: "Code", A: 40, fullMark: 100 },
       { subject: "Hype", A: 70, fullMark: 100 },
       { subject: "Utility", A: 20, fullMark: 100 },
       { subject: "Audit", A: 60, fullMark: 100 },
    ],
    prediction: { yes: 890, no: 10 },
    category: 'Gaming',
    miningEntryCost: 0.05,
    daoRights: true,
    status: 'Funding'
  },
   {
    id: '4',
    title: 'Based Punks',
    description: '10,000 unique collectible characters with proof of ownership stored on the Base blockchain.',
    logo: 'https://picsum.photos/seed/punks/200/200',
    banner: 'https://picsum.photos/seed/punksbanner/1200/400',
    softCap: 10,
    hardCap: 50,
    raised: 55, // Over hardcap
    backers: 1500,
    tokenTicker: '$BPUNK',
    tokenomics: [
      { name: 'Community', value: 90, fill: '#0052FF' },
      { name: 'Team', value: 10, fill: '#333' },
    ],
    comments: [],
    sketchiness: [],
    prediction: { yes: 1500, no: 5 },
    category: 'NFT',
    miningEntryCost: 0.01,
    daoRights: false,
    status: 'Ended'
  },
  {
    id: '5',
    title: 'Yield Base',
    description: 'Automated yield farming strategies for your ETH. Sit back and watch your portfolio grow.',
    logo: 'https://picsum.photos/seed/yield/200/200',
    banner: 'https://picsum.photos/seed/yieldbanner/1200/400',
    softCap: 200,
    hardCap: 1000,
    raised: 150,
    backers: 50,
    tokenTicker: '$YIELD',
    tokenomics: [{ name: 'Pool', value: 100, fill: '#0052FF' }],
    comments: [],
    sketchiness: [],
    prediction: { yes: 45, no: 45 },
    category: 'DeFi',
    miningEntryCost: 1.0,
    daoRights: true,
    status: 'Funding'
  },
  {
    id: '6',
    title: 'FriendBase',
    description: 'The social network where your network is your net worth. Key-based social interactions.',
    logo: 'https://picsum.photos/seed/friend/200/200',
    banner: 'https://picsum.photos/seed/friendbanner/1200/400',
    softCap: 30,
    hardCap: 150,
    raised: 10,
    backers: 200,
    tokenTicker: '$FRND',
    tokenomics: [{ name: 'Users', value: 80, fill: '#0052FF' }, { name: 'Team', value: 20, fill: '#000' }],
    comments: [],
    sketchiness: [],
    prediction: { yes: 100, no: 200 },
    category: 'Social',
    miningEntryCost: 0.05,
    daoRights: true,
    status: 'Funding'
  },
  {
    id: '7',
    title: 'BasePred',
    description: 'Decentralized prediction markets. Bet on the outcome of real-world events.',
    logo: 'https://picsum.photos/seed/pred/200/200',
    banner: 'https://picsum.photos/seed/predbanner/1200/400',
    softCap: 50,
    hardCap: 300,
    raised: 45,
    backers: 90,
    tokenTicker: '$PRED',
    tokenomics: [{ name: 'Liquidity', value: 50, fill: '#0052FF' }, { name: 'Dev', value: 50, fill: '#333' }],
    comments: [],
    sketchiness: [],
    prediction: { yes: 80, no: 20 },
    category: 'Prediction',
    miningEntryCost: 0.2,
    daoRights: true,
    status: 'Funding'
  },
  {
    id: '8',
    title: 'BaseDAO',
    description: 'A governance tooling kit for building decentralized organizations on Base.',
    logo: 'https://picsum.photos/seed/dao/200/200',
    banner: 'https://picsum.photos/seed/daobanner/1200/400',
    softCap: 15,
    hardCap: 75,
    raised: 75,
    backers: 600,
    tokenTicker: '$BDAO',
    tokenomics: [{ name: 'DAO Treasury', value: 100, fill: '#0052FF' }],
    comments: [],
    sketchiness: [],
    prediction: { yes: 500, no: 10 },
    category: 'DAO',
    miningEntryCost: 0.1,
    daoRights: true,
    status: 'Launched'
  }
];